/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedListsListIdRouteImport } from './routes/_authenticated/lists/$listId'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items/new'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items/$itemId'
import { Route as AuthenticatedItemsItemIdEditRouteImport } from './routes/_authenticated/items/$itemId/edit'
import { Route as AuthenticatedListsListIdItemsNewRouteImport } from './routes/_authenticated/lists/$listId/items/new'
import { Route as AuthenticatedListsListIdItemsItemIdRouteImport } from './routes/_authenticated/lists/$listId/items/$itemId'
import { Route as AuthenticatedListsListIdItemsItemIdEditRouteImport } from './routes/_authenticated/lists/$listId/items/$itemId/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListsListIdRoute =
  AuthenticatedListsListIdRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsItemIdEditRoute =
  AuthenticatedItemsItemIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedItemsItemIdRoute,
  } as any)
const AuthenticatedListsListIdItemsNewRoute =
  AuthenticatedListsListIdItemsNewRouteImport.update({
    id: '/items/new',
    path: '/items/new',
    getParentRoute: () => AuthenticatedListsListIdRoute,
  } as any)
const AuthenticatedListsListIdItemsItemIdRoute =
  AuthenticatedListsListIdItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedListsListIdRoute,
  } as any)
const AuthenticatedListsListIdItemsItemIdEditRoute =
  AuthenticatedListsListIdItemsItemIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedListsListIdItemsItemIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRouteWithChildren
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/lists/$listId': typeof AuthenticatedListsListIdRouteWithChildren
  '/items/': typeof AuthenticatedItemsIndexRoute
  '/lists/': typeof AuthenticatedListsIndexRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/lists/$listId/items/$itemId': typeof AuthenticatedListsListIdItemsItemIdRouteWithChildren
  '/lists/$listId/items/new': typeof AuthenticatedListsListIdItemsNewRoute
  '/lists/$listId/items/$itemId/edit': typeof AuthenticatedListsListIdItemsItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRouteWithChildren
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/lists/$listId': typeof AuthenticatedListsListIdRouteWithChildren
  '/items': typeof AuthenticatedItemsIndexRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/lists/$listId/items/$itemId': typeof AuthenticatedListsListIdItemsItemIdRouteWithChildren
  '/lists/$listId/items/new': typeof AuthenticatedListsListIdItemsNewRoute
  '/lists/$listId/items/$itemId/edit': typeof AuthenticatedListsListIdItemsItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authenticated/items/$itemId': typeof AuthenticatedItemsItemIdRouteWithChildren
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/lists/$listId': typeof AuthenticatedListsListIdRouteWithChildren
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
  '/_authenticated/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/_authenticated/lists/$listId/items/$itemId': typeof AuthenticatedListsListIdItemsItemIdRouteWithChildren
  '/_authenticated/lists/$listId/items/new': typeof AuthenticatedListsListIdItemsNewRoute
  '/_authenticated/lists/$listId/items/$itemId/edit': typeof AuthenticatedListsListIdItemsItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/items/$itemId'
    | '/items/new'
    | '/lists/$listId'
    | '/items/'
    | '/lists/'
    | '/items/$itemId/edit'
    | '/lists/$listId/items/$itemId'
    | '/lists/$listId/items/new'
    | '/lists/$listId/items/$itemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/items/$itemId'
    | '/items/new'
    | '/lists/$listId'
    | '/items'
    | '/lists'
    | '/items/$itemId/edit'
    | '/lists/$listId/items/$itemId'
    | '/lists/$listId/items/new'
    | '/lists/$listId/items/$itemId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authenticated/items/$itemId'
    | '/_authenticated/items/new'
    | '/_authenticated/lists/$listId'
    | '/_authenticated/items/'
    | '/_authenticated/lists/'
    | '/_authenticated/items/$itemId/edit'
    | '/_authenticated/lists/$listId/items/$itemId'
    | '/_authenticated/lists/$listId/items/new'
    | '/_authenticated/lists/$listId/items/$itemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/$listId': {
      id: '/_authenticated/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AuthenticatedListsListIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId': {
      id: '/_authenticated/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId/edit': {
      id: '/_authenticated/items/$itemId/edit'
      path: '/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedItemsItemIdRoute
    }
    '/_authenticated/lists/$listId/items/new': {
      id: '/_authenticated/lists/$listId/items/new'
      path: '/items/new'
      fullPath: '/lists/$listId/items/new'
      preLoaderRoute: typeof AuthenticatedListsListIdItemsNewRouteImport
      parentRoute: typeof AuthenticatedListsListIdRoute
    }
    '/_authenticated/lists/$listId/items/$itemId': {
      id: '/_authenticated/lists/$listId/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/lists/$listId/items/$itemId'
      preLoaderRoute: typeof AuthenticatedListsListIdItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedListsListIdRoute
    }
    '/_authenticated/lists/$listId/items/$itemId/edit': {
      id: '/_authenticated/lists/$listId/items/$itemId/edit'
      path: '/edit'
      fullPath: '/lists/$listId/items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedListsListIdItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedListsListIdItemsItemIdRoute
    }
  }
}

interface AuthenticatedItemsItemIdRouteChildren {
  AuthenticatedItemsItemIdEditRoute: typeof AuthenticatedItemsItemIdEditRoute
}

const AuthenticatedItemsItemIdRouteChildren: AuthenticatedItemsItemIdRouteChildren =
  {
    AuthenticatedItemsItemIdEditRoute: AuthenticatedItemsItemIdEditRoute,
  }

const AuthenticatedItemsItemIdRouteWithChildren =
  AuthenticatedItemsItemIdRoute._addFileChildren(
    AuthenticatedItemsItemIdRouteChildren,
  )

interface AuthenticatedListsListIdItemsItemIdRouteChildren {
  AuthenticatedListsListIdItemsItemIdEditRoute: typeof AuthenticatedListsListIdItemsItemIdEditRoute
}

const AuthenticatedListsListIdItemsItemIdRouteChildren: AuthenticatedListsListIdItemsItemIdRouteChildren =
  {
    AuthenticatedListsListIdItemsItemIdEditRoute:
      AuthenticatedListsListIdItemsItemIdEditRoute,
  }

const AuthenticatedListsListIdItemsItemIdRouteWithChildren =
  AuthenticatedListsListIdItemsItemIdRoute._addFileChildren(
    AuthenticatedListsListIdItemsItemIdRouteChildren,
  )

interface AuthenticatedListsListIdRouteChildren {
  AuthenticatedListsListIdItemsItemIdRoute: typeof AuthenticatedListsListIdItemsItemIdRouteWithChildren
  AuthenticatedListsListIdItemsNewRoute: typeof AuthenticatedListsListIdItemsNewRoute
}

const AuthenticatedListsListIdRouteChildren: AuthenticatedListsListIdRouteChildren =
  {
    AuthenticatedListsListIdItemsItemIdRoute:
      AuthenticatedListsListIdItemsItemIdRouteWithChildren,
    AuthenticatedListsListIdItemsNewRoute:
      AuthenticatedListsListIdItemsNewRoute,
  }

const AuthenticatedListsListIdRouteWithChildren =
  AuthenticatedListsListIdRoute._addFileChildren(
    AuthenticatedListsListIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRouteWithChildren
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedListsListIdRoute: typeof AuthenticatedListsListIdRouteWithChildren
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRouteWithChildren,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedListsListIdRoute: AuthenticatedListsListIdRouteWithChildren,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
